//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenceTracker.DAL.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sickness
    {
        public string Id { get; set; }
        public string AbsenceId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Time { get; set; }
    
        public virtual Absence Absence { get; set; }
    }
}
