//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenceTracker.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Absence
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string AssigneeId { get; set; }
        public string Type { get; set; }
        public string Status { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUserAssignee { get; set; }
        public virtual Compensation Compensation { get; set; }
        public virtual Sickness Sickness { get; set; }
        public virtual Vacation Vacation { get; set; }
    }
}
