//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AbsenceTracker.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompensationEntry
    {
        public string Id { get; set; }
        public string CompensationId { get; set; }
        public System.DateTime Date { get; set; }
        public int SpentTime { get; set; }
    
        public virtual Compensation Compensation { get; set; }
    }
}
